### ISSUE TITLE
The plugin “com.victorgrycuk.colorpicker” is not available for download.

### ISSUE THREAD

**Issue by almostsultry** [VictorGrycuk/streamdeck-color-picker#11]
I just learned of your app. Can I have it back, please?

**Comment by VictorGrycuk** [comment]
Hi @almostsultry, I had no idea it was not available for download anymore. I will have to look into it.
Meanwhile, you can check and download the last version from [here](https://github.com/VictorGrycuk/streamdeck-color-picker/releases/tag/1.4.1) and see if you can install it manually.

**Comment by almostsultry** [comment]
It may be a problem with ARM compatibility. I got this error trying to install the plugin manually:

![Screen Shot 2022-10-03 at 7 46 05 AM](https://user-images.githubusercontent.com/4964731/193569602-f436d2e7-d153-429a-8a02-6cd937b798db.png)

**Comment by gr4y41** [comment]
> It may be a problem with ARM compatibility. I got this error trying to install the plugin manually:
> 
> ![Screen Shot 2022-10-03 at 7 46 05 AM](https://user-images.githubusercontent.com/4964731/193569602-f436d2e7-d153-429a-8a02-6cd937b798db.png)

I am having the same issue. It appears to be because of ARM like you suggested. @VictorGrycuk I am color blind as well so this is a game changer. I will try and take a crack at it and see what it would take to port to the M1 chip.

**Comment by VictorGrycuk** [comment]
Thanks @almostsultry and @mbelltbg. The plugin was made using a .NET Framework library, so it won't work on non-Windows machines or without Net Framework installed, sadly.

@mbelltbg if you can port it, that would be great as several people have been asking for a macOS compatible version.

**Comment by gr4y41** [comment]
@VictorGrycuk I was able to get something working with keyboard maestro. Definitely not as stream-lined as your plug-in is. I'll post it on my repository and link here if you would like.

**Comment by VictorGrycuk** [comment]
@mbelltbg That sounds great, I can link it in the read me as an alternative.

**Comment by gr4y41** [comment]
@VictorGrycuk Here is the link to the repository. I am still trying to teach myself some javascript to port this to an actual plugin. 

https://github.com/mbelltbg/mac-streamdeck-color-picker.git

**Comment by VictorGrycuk** [comment]
Thank you @mbelltbg, I added the link to the readme.
Hopefully future Mac users will use it as an alternative.
