### ISSUE TITLE
detected as virus

### ISSUE THREAD

**Issue by cid-wings** [VictorGrycuk/streamdeck-color-picker#12]
Im using this plugin for now more than 1 year and have no problem but today
kaspersky uninstall it beceause he act like a virus here the report in french

Événement: Un objet malveillant a été détecté
Application: Color Picker
Utilisateur: DESKTOP-********\****
Type d'utilisateur: Utilisateur actif
Module: Surveillance du système
Résultat de description: Détecté
Type: Virus
Nom: PDM:Worm.Win32.BSS.ScreenLock
Niveau de menace: Élevé
Type d'objet: Processus
Chemin de l'objet: c:\users\duthi\appdata\roaming\elgato\streamdeck\plugins\com.victorgrycuk.colorpicker.sdplugin
Nom de l'objet: streamdeck.colorpicker.exe
Raison: Bases
Date de publication des bases: Aujourd'hui, 22/10/2022 15:43:00

**Comment by VictorGrycuk** [comment]
Thanks for reporting it, @cid-wings.
Looks like a false positive, detected on several games when pressing `Ctrl+Shift+F4`.

Have you by any chance used that key combination with the plugin?

**Comment by cid-wings** [comment]
Hi thanks for the answer !
I cannot say it at 100% I was not pressing these combination :/.
but i do remember i was changing an option an hour before like colorpicker get color in real time from the postion of my cursor and I play with it like 2 minutes and disable it but the alert do not pop up at this time he came up hour later .
maybe I have a real virus try to infect other program don't know but I format my computer and I re install colorpicker .
Now Kaspersky say nothing for him its all clear so far so good

**Comment by VictorGrycuk** [comment]
Thanks @cid-wings.
It does look like kapersky detected a false positive, possibly due to the library that reads the screen pixel.
If it keeps flagging it, try adding the `streamdeck.colorpicker.exe` file to the ignore files in kapersky.

I will be closing the issue. Let me know if you need help with anything else.
