### ISSUE TITLE
Is it possible to retain picked color after restart the software?

### ISSUE THREAD

**Issue by OnyxAmber** [VictorGrycuk/streamdeck-color-picker#16]
I'm using color picker in artistic workflow, and I've found it to work really well as a color palette, like, create a page of picker buttons and take whatever colors from reference images or artworks.
The thing is, after restart the software, these picked colors were gone as well. 
Is it possible to add an option or something so that these colors can be preserved after restart the software?

**Comment by VictorGrycuk** [comment]
Hi @OnyxAmber!
I think that it is possible. I had to do the same on a different plugin, and it worked; however, it was not tested on multiple instances of the same plugin.

I will make the necessary modifications, test it, and let you know as soon as I can.

**Comment by VictorGrycuk** [comment]
@OnyxAmber I have been testing the new feature, but it seems to be unreliable at the moment. I might need more time.

However, I have been thinking, since it seems that this plugin is being used by artists to select colours, it might just be easier to create a new plugin exclusively to select and store colours.

**Comment by OnyxAmber** [comment]
> @OnyxAmber I have been testing the new feature, but it seems to be unreliable at the moment. I might need more time.
> 
> However, I have been thinking, since it seems that this plugin is being used by artists to select colours, it might just be easier to create a new plugin exclusively to select and store colours.

Got it, thank you very much, looking forward to your new plugin!

**Comment by VictorGrycuk** [comment]
@OnyxAmber, I update the plugin with a new action: Color Palette.
![image](https://github.com/VictorGrycuk/streamdeck-color-picker/assets/39467613/61a1e411-e5d9-4623-a81e-ea2c4d6f946c)

The new action is very similar to the color picker, but it's much simpler.
On a quick key press, it will show the selected color and its hexadecimal value on the key, and also copy the value to the clipboard.
On a longer key press, it will copy its value to the clipboard. You have to press the key for 250ms for it to be considered a long press. I initially used 1 second, but I thought that copying different values all the time it would be tiresome, and also a quick tap of the key is enough for it to be a quick press.

It will persist the stored color even after reopening the StreamDeck app, and as a side effect of that, the stored value can be accessed from the action configuration:

![image](https://github.com/VictorGrycuk/streamdeck-color-picker/assets/39467613/e2dbe5c2-a0d3-4586-83a1-729f848436cb)

I am attaching the plugin here. The steps to install it are:
1. Uninstall any other version of the plugin
2. Unzip the attached file and run the `.streamDeckPlugin` file
3. And accept when the StreamDeck asks if you want to install it

Please let me know if it works correctly, as well as any other improvements.
Once I have your confirmation, I will publish it to the Elgato store.

[com.victorgrycuk.colorpicker.zip](https://github.com/VictorGrycuk/streamdeck-color-picker/files/14153518/com.victorgrycuk.colorpicker.zip)

**Comment by OnyxAmber** [comment]
> @OnyxAmber, I update the plugin with a new action: Color Palette. ![image](https://private-user-images.githubusercontent.com/39467613/302059770-61a1e411-e5d9-4623-a81e-ea2c4d6f946c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxMjY5MzYsIm5iZiI6MTcwNzEyNjYzNiwicGF0aCI6Ii8zOTQ2NzYxMy8zMDIwNTk3NzAtNjFhMWU0MTEtZTVkOS00NjIzLWE4MWUtZWEyYzRkNmY5NDZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA1VDA5NTAzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4Y2RhNDdkNmNiY2FiMmVjOTIyMzFiYjc4YTAxOGIzOGVmNTA4YmU5ZTM5YTQ3MmVhZTcxNWE0MTRkZGE5MmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WQx2I1sqbkO8LgECLH9Z_XZlvdFjKYXlQxNUfkxqoE0)
> 
> The new action is very similar to the color picker, but it's much simpler. On a quick key press, it will show the selected color and its hexadecimal value on the key, and also copy the value to the clipboard. On a longer key press, it will copy its value to the clipboard. You have to press the key for 250ms for it to be considered a long press. I initially used 1 second, but I thought that copying different values all the time it would be tiresome, and also a quick tap of the key is enough for it to be a quick press.
> 
> It will persist the stored color even after reopening the StreamDeck app, and as a side effect of that, the stored value can be accessed from the action configuration:
> 
> ![image](https://private-user-images.githubusercontent.com/39467613/302060574-e2dbe5c2-a0d3-4586-83a1-729f848436cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxMjY5MzYsIm5iZiI6MTcwNzEyNjYzNiwicGF0aCI6Ii8zOTQ2NzYxMy8zMDIwNjA1NzQtZTJkYmU1YzItYTBkMy00NTg2LTgzYTEtNzI5Zjg0ODQzNmNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA1VDA5NTAzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjNGYwNGEwZGVjZDcyNTk2MTYyMDI3MzlhNzc3YjJjMWJjZDQwZmNkYzY5MGRhNjBlYmVlZDdlOThmYWM2NWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3ZHd2FlKtFX2OtF6ZHXLQ_o7a1KvayUKAQ3_RYNvtTs)
> 
> I am attaching the plugin here. The steps to install it are:
> 
> 1. Uninstall any other version of the plugin
> 2. Unzip the attached file and run the `.streamDeckPlugin` file
> 3. And accept when the StreamDeck asks if you want to install it
> 
> Please let me know if it works correctly, as well as any other improvements. Once I have your confirmation, I will publish it to the Elgato store.
> 
> [com.victorgrycuk.colorpicker.zip](https://github.com/VictorGrycuk/streamdeck-color-picker/files/14153518/com.victorgrycuk.colorpicker.zip)

Hi @VictorGrycuk , I've tried this new version and it works perfectly for me.
Many thanks!

**Comment by VictorGrycuk** [comment]
Great to know!
I will be releasing a new version with this change soon.
