### ISSUE TITLE
Upon launch, when button is clicked, only a warning icon is displayed on the button

### ISSUE THREAD

**Issue by oneiric-pilgrim** [VictorGrycuk/streamdeck-color-picker#18]
When I press the button, only a warning icon is displayed on the button, no hex/rgb/name values appearing.

**Comment by VictorGrycuk** [comment]
Hi @d3vildoodle, sorry about that.
Could you please attach me the plugin log? You should find it here:
`C:\Users\{user}\AppData\Roaming\Elgato\StreamDeck\Plugins\com.victorgrycuk.colorpicker.streamDeckPlugin\pluginlog.log`

Hopefully it will give is information about what's happening.

**Comment by AdamArcane** [comment]
I am experiencing the same issue. Just installed the plugin and upon clicking the button, only a warning icon is displayed.

I've attached my plugin log
[pluginlog.log](https://github.com/VictorGrycuk/streamdeck-color-picker/files/14638889/pluginlog.log)

**Comment by VictorGrycuk** [comment]
Thanks @ATommasi.
Have you tried a previous version? Previous versions can be found [here](https://github.com/VictorGrycuk/streamdeck-color-picker/releases).
I would like to know if it is a problem introduced in the last version(s), or something else.

**Comment by AdamArcane** [comment]
I've installed every version back to 1.5 and am experiencing the same problem with each one. So it must be related to my setup somehow?

I drag the action to the buttons and did not change any settings. 

Is there anything else I can try?

**Comment by VictorGrycuk** [comment]
Thanks, then it cannot be anything introduced in the latests version.

That's the thing, it is a pretty straight forward plugin, it should work.
In the logs that you shared, I am seeing that the plugin keeps getting disconnected every 10 seconds.

I will try updating the BarRaider plugin, the streamdeck framework that this plugin uses, and I will share it here as soon as I can.
Meanwhile, which Windows and .NET version are you using? It might be related to that as well.

**Comment by AdamArcane** [comment]
I'm running win 11 with .net Framework 4.8

**Comment by VictorGrycuk** [comment]
Thanks.
I am attaching a version with updated libraries. Uninstall the current one and install this one and give it a try.
[com.victorgrycuk.colorpicker.zip](https://github.com/VictorGrycuk/streamdeck-color-picker/files/14643847/com.victorgrycuk.colorpicker.zip)

**Comment by AdamArcane** [comment]
Thanks Victor, this version works great for me!

**Comment by VictorGrycuk** [comment]
Great to hear!
I will be releasing a new version to the marketplace soon.

Thanks for reporting this issue, I will be closing it now.
