### ISSUE TITLE
Hex font size is super small

### ISSUE THREAD

**Issue by MatteCrystal** [VictorGrycuk/streamdeck-color-picker#4]
![image](https://user-images.githubusercontent.com/32424764/97772419-dc0bf880-1b14-11eb-85aa-64c9d785977d.png)

I'm using streamdeck XL. All other formats rgb and name seem to fill the box very well but hex is super small and has tons of space it could be using. At the size it's displaying currently It's useless to even use.

**Comment by MatteCrystal** [comment]
I take it back rgb is really small too 
![image](https://user-images.githubusercontent.com/32424764/97772453-648a9900-1b15-11eb-8f76-8db413dc661a.png)

color name is the only acceptable size
![image](https://user-images.githubusercontent.com/32424764/97772461-7bc98680-1b15-11eb-8800-75dd2197149b.png)

**Comment by VictorGrycuk** [comment]
@MatteCrystal That is weird, I would assume it has to do with the screen resolution, but I tested it on different resolutions and had no issues.

The difference between hex/rgb and names is that the font size is automatic. I will see if I can make it work with hex/rgb as well, or find some other solution.

**Comment by VictorGrycuk** [comment]
Hi @MatteCrystal, I just pre-released the version [1.4.0-Beta](https://github.com/VictorGrycuk/streamdeck-color-picker/releases/tag/1.4.0-Beta), could you please test it and see if it fixes your issue?

I cannot reproduce it, however, I suspect it has to do with either your screen resolution or your version of stream deck. Probably the latter as I have the 3x5, and they might use a different resolution inside. I am not sure.

In any case, I applied the text resizing to both the hex and RGB. I hope it fixes your issue.

**Comment by MatteCrystal** [comment]
The new version seems to work. I tested on a streamdeck XL and streamdeck mini

**Comment by VictorGrycuk** [comment]
Awesome, glad to hear it solved the issue.

I will mark this issue as resolved, and then incorporate the new version as official.
