### ISSUE TITLE
Mac Version??

### ISSUE THREAD

**Issue by Raiden38** [VictorGrycuk/streamdeck-color-picker#6]
Is there any way to run this on a stream deck connected to a Mac??

**Comment by VictorGrycuk** [comment]
@Raiden38 I am sorry to inform you that no, it's not possible at this moment.
This is because this plugin uses [StreamDeck Tools](https://github.com/BarRaider/streamdeck-tools) wrapper for C#, and it also uses a couple of .NET libraries.
