### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by SrGeneroso** [VictorGrycuk/streamdeck-color-picker#7]
I love this plugin, in fact I'm researching the streamdeck and barraider plugin solution to try to improve your plugin, or at least modify it to suit me better. I've seen some other barraider plugins can run different actions depend on how long you press the key. I think for the color picker would be awesome to long push the key to update the color picked where the mouse is and short push to copy it to the clipboard, that way, you can quickly copy various colors into the streamdeck and later shortkeing to copy the values into the code.
Anyway, I'll try to learn more and if I finally achieve something I'll let you know.

**Comment by VictorGrycuk** [comment]
@SrGeneroso That sounds great!

The original point of the plugin was to be able to show the colours name, and then the other features were added. At one point I thought about making it more like a colour palette tool, however, I decided to stick to the original idea until I had time to dedicate more time to it.

Feel free to open a pull request, or even fork it.
