### ISSUE TITLE
how to install?

### ISSUE THREAD

**Issue by maxandersen** [VictorGrycuk/streamdeck-color-picker#9]
its not in the store afaics - just install from source seem to fail.

Any instructions or its just not working with latest streamdeck?

**Comment by VictorGrycuk** [comment]
Hi @maxandersen, it appears in the store for me.
By any chance are you on macOS or Linux? It won't appear on those OSes, as this was developed using a .NET framework.

If you are on Windows and still cant find it on the store, you can find the latest version [here](https://github.com/VictorGrycuk/streamdeck-color-picker/releases/tag/1.4.1). Opening the `com.victorgrycuk.colorpicker.streamDeckPlugin` file should install the plug in.

**Comment by maxandersen** [comment]
Ah. Yes. I'm on OS X. That explains it :)

**Comment by VictorGrycuk** [comment]
Hopefully in the future I will be able to release a cross platform version.
But for now I will close the issue.
